name: Deply to GitHub Container Registry
on: [ push ]
tags:
    - v*.*

jobs:
 publish-container-image:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout sources
     uses: actions/checkout@v3
     with:
      fetch-depth: 0       

   - name: Login to GitHub Container Registry
     uses: docker/login-action@v1
     with:
       registry: ghcr.io
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}

   - name: Build the container image
     run: |
      docker build . --tag ghcr.io/project-omotes/omotes-simulator-worker:latest
      docker run ghcr.io/project-omotes/omotes-simulator-worker:latest
      docker push ghcr.io/project-omotes/omotes-simulator-worker:latest

